-- Active: 1708902720363@@127.0.0.1@3306@MUBI
-- Tabla Productora
CREATE TABLE Productora (
    ID_PRODUCTORA INT,
    NOMBRE VARCHAR(255),
    FUNDACION DATE,
    PAIS VARCHAR(50)
);

-- Tabla Director
CREATE TABLE Director (
    ID_DIRECTOR INT,
    NOMBRE VARCHAR(255),
    NACIONALIDAD VARCHAR(50),
    FECHA_NACIMIENTO DATE
);

-- Tabla Genero
CREATE TABLE Genero (
    ID_GENERO INT,
    NOMBRE VARCHAR(255)
);

-- Tabla Peliculas
CREATE TABLE Peliculas (
    ID_PELICULA INT,
    ID_DIRECTOR INT,
    ID_PRODUCTORA INT,
    ID_GENERO INT,
    TITULO VARCHAR(255),
    ANIO INT,
    DURACION INT,
    DESCRIPCION VARCHAR(255),
    CLASIFICACION_EDAD VARCHAR(50)
);

-- Tabla Usuarios
CREATE TABLE Usuarios (
    ID_USUARIO INT,
    NOMBRE_USUARIO VARCHAR(255),
    EMAIL VARCHAR(50),
    FECHA_NACIMIENTO DATE,
    GENERO VARCHAR(30)
);

-- Tabla Vistas
CREATE TABLE Vistas (
    ID_VISTA INT,
    ID_USUARIO INT,
    ID_PELICULA INT,
    FECHA DATE
);

-- Tabla Resenias
CREATE TABLE Resenias (
    ID_RESENIA INT,
    ID_USUARIO INT,
    ID_PELICULA INT,
    CALIFICACION FLOAT,
    COMENTARIO VARCHAR(255),
    FECHA DATE
);

-- Agregar primary keys
ALTER TABLE Productora ADD PRIMARY KEY (ID_PRODUCTORA);
ALTER TABLE Director ADD PRIMARY KEY (ID_DIRECTOR);
ALTER TABLE Genero ADD PRIMARY KEY (ID_GENERO);
ALTER TABLE Peliculas ADD PRIMARY KEY (ID_PELICULA);
ALTER TABLE Usuarios ADD PRIMARY KEY (ID_USUARIO);
ALTER TABLE Vistas ADD PRIMARY KEY (ID_VISTA);
ALTER TABLE Resenias ADD PRIMARY KEY (ID_RESENIA);

-- Agregar foreign keys
ALTER TABLE Peliculas ADD CONSTRAINT FK_Peliculas_Director FOREIGN KEY (ID_DIRECTOR) REFERENCES Director(ID_DIRECTOR);
ALTER TABLE Peliculas ADD CONSTRAINT FK_Peliculas_Productora FOREIGN KEY (ID_PRODUCTORA) REFERENCES Productora(ID_PRODUCTORA);
ALTER TABLE Peliculas ADD CONSTRAINT FK_Peliculas_Genero FOREIGN KEY (ID_GENERO) REFERENCES Genero(ID_GENERO);
ALTER TABLE Vistas ADD CONSTRAINT FK_Vistas_Usuarios FOREIGN KEY (ID_USUARIO) REFERENCES Usuarios(ID_USUARIO);
ALTER TABLE Vistas ADD CONSTRAINT FK_Vistas_Peliculas FOREIGN KEY (ID_PELICULA) REFERENCES Peliculas(ID_PELICULA);
ALTER TABLE Resenias ADD CONSTRAINT FK_Resenias_Usuarios FOREIGN KEY (ID_USUARIO) REFERENCES Usuarios(ID_USUARIO);
ALTER TABLE Resenias ADD CONSTRAINT FK_Resenias_Peliculas FOREIGN KEY (ID_PELICULA) REFERENCES Peliculas(ID_PELICULA);
